enclave:
  spid: "12345678901234567890123456789012"        # Service Provider ID
  certificate: "/home/wtest/signal/ContactDiscoveryService/service/config/mock_certificate.pem"
# Service Provider Certificate
  key: "/home/wtest/signal/ContactDiscoveryService/service/config/mock_private_key.pem"        # Service Provider Key
  iasHost: localhost    # IAS Host to talk to (testing or production)
  acceptGroupOutOfDate: true # Whether to serve IAS responses with GROUP_OUT_OF_DATE instead of OK [true|false]
  instances:
   - mrenclave: 1 # mrenclave value 1
     debug: true    # Whether this is a debug or production enclave [true|false]
  #  - mrenclave: # mrenclave value 2
  #    debug: true    # Whether this is a debug or production enclave [true|false]

signal:
  userToken: 06a19fc7e8e34c705fa283af938dfd07   # head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'
  serverToken: cc3d9c86a0409a7aab9240bef0401806 # head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'

redis: 
  masterName: mymaster  # Redis Sentinel master name
  sentinelUrls:
   - localhost:26379 # Redis Sentinel host:port 1
   - localhost:26380 # Redis Sentinel host:port 2
   - localhost:26381 # Redis Sentinel host:port 3

directory:
  initialSize: 10000000
  minLoadFactor: 0.75
  maxLoadFactor: 0.85  
  sqs:
    accessKey: 624364587793      # AWS SQS accessKey
    accessSecret: secretdev  # AWS SQS accessSecret
    queueUrl: https://sqs.ap-southeast-1.amazonaws.com      # AWS SQS queue url
    queueRegion: ap-southeast-1

limits:
  contactQueries:
    bucketSize: 1000       # Leaky bucket size
    leakRatePerMinute: 100 # Leaky bucket rate per minute
  remoteAttestations:
    bucketSize: 1000       # Leaky bucket size
    leakRatePerMinute: 10 # Leaky bucket rate per minute

# metrics:
#   reporters:
#     - type:     json # wavefront metrics reporter
#       hostname:      # wavefront endpoint hostname
#       token:         # wavefront endpoint token
